name: Kamus Pesbuk API CI

on: 
  pull_request: 
    branches: ["master"]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with: 
          bun-version: 1.1.334

      - run : bun install
      - run : bun run test
      - run : bun run lint
